name: Feature request
description: Suggest a new feature or improvement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Use this template for product or developer-experience improvements.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation or pain point are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the preferred solution and expected behavior
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives did you evaluate?
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What would make this request complete?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
